name: ponymessenger
version: 1
handle:
 - rewrite: if( path == "/_sae/channel/connected" ) goto "/index.php/PubSub_Channel/connected"
 - rewrite: if( path == "/_sae/channel/disconnected" ) goto "/index.php/PubSub_Channel/disconnected"
 - rewrite: if( path == "/_sae/channel/message" ) goto "/index.php/PubSub_Channel/message"
